# Doctrine Cache Configurator
doctrine_cache:
    providers:
        my_markdown_cache:
            type: '%cache_type%'
            file_system:
                directory: '%kernel.cache_dir%/doctrine_cache'